-- Dictionary Search: Kosa Kata CBAS (686 baris)
INSERT INTO terms (term_id, term_en, term_kr, category)
VALUES
('Nama Debitur', 'Debtor Name', '채무자 이름', 'field'),
('Masukkan Nama Debitur', 'Enter Debtor Name', '채무자 이름 입력', 'field'),
('Nomor Surat', 'Letter Number', '문서 번호', 'field'),
('Masukkan Nomor Surat', 'Enter Letter Number', '문서 번호를 입력하세요', 'field'),
('no', 'no', '숫자', 'field'),
('id', 'id', '아이디', 'field'),
('Kode', 'Code', '암호', 'field'),
('Nama', 'Name', '이름', 'field'),
('NIK', 'NIK', '주민등록번호', 'field'),
('Masukkan NIK', 'Enter NIK', '주민등록번호 입력', 'field'),
('NPWP', 'NPWP', '세금 식별 번호', 'field'),
('Masukkan NPWP', 'Enter NPWP', '세금 식별 번호를 입력하세요', 'field'),
('Passport', 'Passport', '여권', 'field'),
('Masukkan Passport', 'Enter Passport', '여권을 입력하세요', 'field'),
('Tanggal Mulai', 'Start Date', '시작일', 'field'),
('Pilih Tanggal', 'Select Date', '날짜 선택', 'field'),
('Tanggal Berakhir', 'End Date', '만료일', 'field'),
('User Input', 'User Input', '사용자 입력', 'field'),
('Pilih User', 'Select User', '사용자 선택', 'field'),
('Produk', 'Product', '제품', 'field'),
('Pilih Produk', 'Select Product', '제품 선택', 'field'),
('Tujuan Permintaan', 'Request Purpose', '요청 목적', 'field'),
('Pilih Tujuan Permintaan', 'Select Request Purpose', '요청 목적 선택', 'field'),
('Format', 'Format', '형식', 'field'),
('Masukkan Format', 'Enter Format', '형식 입력', 'field'),
('Tanggal Lahir', 'Date of Birth', '생일', 'field'),
('status', 'status', '상태', 'field'),
('aksi', 'action', '행동', 'field'),
('Ganti status', 'Change status', '상태 변경', 'field'),
('Konfirmasi Ganti Status', 'Confirm Change Status', '상태 변경 확인', 'field'),
('Apakah anda yakin untuk', 'Are you sure you want to', '이 데이터의 상태를', 'field'),
('mengganti status pada data', 'change the status of this', '변경하시겠습니까?', 'field'),
('ini?', 'data?', '', 'field'),
('Kata Kunci', 'keyword', '키워드', 'field'),
('Masukkan Kata Kunci', 'Enter keyword', '키워드를 입력하세요', 'field'),
('Pilih status', 'Select status', '상태 선택', 'field'),
('Masukkan kode', 'Enter Code', '코드를 입력하세요', 'field'),
('edit', 'edit', '편집하다', 'field'),
('pertanggal', 'As of date', '날짜 기준', 'field'),
('Masukkan pertanggal', 'Enter as of date', '날짜를 입력하세요', 'field'),
('Perbarui', 'Update', '업데이트', 'field'),
('perhari', 'More days', '하루에', 'field'),
('Export', 'Export', '수출', 'field'),
('Masukkan id', 'Enter id', '아이디를 입력하세요', 'field'),
('Masukkan per hari', 'Enter more days', '하루에 입력', 'field'),
('Tambah', 'Add', '추가하다', 'field'),
('Masukkan nama', 'Enter name', '이름을 입력하세요', 'field'),
('Request', 'Request', '요청', 'field'),
('Masukkan Request', 'Enter Request', '요청을 입력하세요', 'field'),
('Input Request Inquiry', 'Input Request Inquiry', '입력 요청 문의', 'field'),
('Jenis Nasabah', 'Debtor Type', '고객 유형', 'field'),
('Pilih Tipe Debitur', 'Select Debtor Type', '채무자 유형 선택', 'field'),
('Tipe Pencarian', 'Robot Find Result', '검색 유형', 'field'),
('Pilih Tipe Pencarian', 'Select Robot Find Result', '검색 유형 선택', 'field'),
('Simpan', 'Save', '구하다', 'field'),
('Mode Kecocokan', 'Match Mode', '일치 모드', 'field'),
('Pilih Mode Kecocokan', 'Select Match Mode', '호환 모드 선택', 'field'),
('Saluran', 'Channel', '채널', 'field'),
('Pilih Saluran', 'Select Channel', '채널 선택', 'field'),
('Cabang', 'Branch', '지점', 'field'),
('Pilih Cabang', 'Select Branch', '지점 선택', 'field'),
('Tipe Customer', 'Customer Type', '고객 유형', 'field'),
('Pilih Tipe Customer', 'Select Customer Type', '고객 유형 선택', 'field'),
('value', 'value', '값', 'field'),
('Masukkan value', 'Enter value', '값을 입력하세요', 'field'),
('Nama Customer', 'Customer Name', '고객 이름', 'field'),
('Masukkan Nama Customer', 'Enter Customer Name', '고객 이름 입력', 'field'),
('Tipe Identitas', 'Identity Type', '신분 유형', 'field'),
('Pilih Tipe Identitas', 'Select Identity Type', '신분 유형 선택', 'field'),
('KTP', 'KTP', '주민등록증', 'field'),
('Masukkan nomor KTP', 'Enter KTP Number', '신분증 번호를 입력하세요', 'field'),
('Flag Identity Number', 'Flag Identity Number', '플래그 식별 번호 예외', 'field'),
('Exception', 'Exception', '', 'field'),
('Masukkan Flag Identity', 'Enter Flag Identity Number', '플래그 신원 번호 예외', 'field'),
('Number Exception', 'Exception', '입력', 'field'),
('Jenis Kelamin', 'Gender', '성별', 'field'),
('Pilih Jenis Kelamin', 'Select Gender', '성별 선택', 'field'),
('Tempat Lahir', 'Place of Birth', '출생지', 'field'),
('Masukkan Tempat Lahir', 'Enter Place of Birth', '출생지 입력', 'field'),
('Tanggal Berdiri', 'Date of Establishment', '설립일', 'field'),
('Jenis Badan Usaha', 'Types of Business Entities', '사업체 유형', 'field'),
('Created date', 'Created date', '생성일', 'field'),
('Pilih Jenis Badan Usaha', 'Select Type of Business', '사업체 유형 선택', 'field'),
('', 'Entity', '', 'field'),
('Status Perkawinan', 'Marital Status', '혼인 상태', 'field'),
('Pilih Status Perkawinan', 'Select Marital Status', '결혼 상태 선택', 'field'),
('Kewarganegaraan', 'Nationality', '국적', 'field'),
('Pilih Kewarganegaraan', 'Select Nationality', '국적 선택', 'field'),
('Nama Gadis Ibu Kandung', 'Mother Name', '어머니의 이름', 'field'),
('Masukkan Nama Gadis Ibu', 'Enter Mother Name', '어머니 이름을 입력하세요', 'field'),
('Kandung', '', '', 'field'),
('Nomor Telepon', 'Phone Number', '전화 번호', 'field'),
('Masukkan Nomor Telepon', 'Enter Phone Number', '전화번호를 입력하세요', 'field'),
('Alamat', 'Address', '주소', 'field'),
('Masukkan Alamat', 'Enter Address', '주소를 입력하세요', 'field'),
('Provinsi', 'Province', '주', 'field'),
('Pilih Provinsi', 'Select Province', '주 선택', 'field'),
('Kota', 'City', '도시', 'field'),
('Pilih Kota', 'Select City', '도시 선택', 'field'),
('Kecamatan', 'District', '구', 'field'),
('Pilih Kecamatan', 'Select District', '구를 선택하세요', 'field'),
('Kelurahan', 'Village', '행정동', 'field'),
('Pilih Kelurahan', 'Select Village', '동 선택', 'field'),
('Kirim Data Non Debitur', 'Send Non-Debtor Data', '비채무자 데이터 전송', 'field'),
('Ip address', 'Ip address', '인터넷 프로토콜 주소', 'field'),
('Dokumen', 'Documents', '문서', 'field'),
('Masukkan ip address', 'Enter ip address', '인터넷 프로토콜 주소를 입력하세요', 'field'),
('Tipe Debitur', 'Debtor Type', '채무자 유형', 'field'),
('Url api', 'Url api', '통합 자원 식별자 애플리케이션 프로그래밍 인터페이스', 'field'),
('Upload Data Request', 'Upload Data Request', '데이터 업로드 요청', 'field'),
('File', 'File', '파일', 'field'),
('Pilih File', 'Select File', '파일 선택', 'field'),
('Line', 'Line', '라인', 'field'),
('Kode Produk', 'Product Code', '제품 코드', 'field'),
('User slik', 'User slik', '사용자 클릭', 'field'),
('Masukkan user slik', 'Enter user slik', '사용자 slik을 입력하세요', 'field'),
('Nama user', 'Username', '사용자 이름', 'field'),
('Nama Lengkap', 'Full Name', '성명', 'field'),
('Is Flag Identity Number', 'Is Flag Identity Number', '플래그 식별 번호인가요', 'field'),
('role', 'role', '역할', 'field'),
('Pilih role', 'Select role', '역할 선택', 'field'),
('Valid', 'Valid', '유효한', 'field'),
('Tidak Valid', 'Not Valid', '유효하지 않음', 'field'),
('Pesan Error', 'Message Error', '에러 메시지', 'field'),
('Approve Data Request', 'Approve Data Request', '데이터 요청 승인', 'field'),
('Tanggal Input', 'Input Date', '입력 날짜', 'field'),
('Stage', 'Stage', '무대', 'field'),
('Masukkan nama user', 'Enter username', '사용자 이름을 입력하세요', 'field'),
('Password slik', 'Password slik', '비밀번호를 클릭하세요', 'field'),
('Masukkan password slik', 'Enter password slik', '비밀번호를 입력하세요 slik', 'field'),
('Password ideb', 'Password ideb', 'ideb 비밀번호', 'field'),
('Masukkan password ideb', 'Enter password ideb', '비밀번호 ideb를 입력하세요', 'field'),
('Informasi Customer', 'Customer Information', '고객 정보', 'field'),
('Data Nasabah', 'Customer Data', '고객 데이터', 'field'),
('Supervisor', 'Supervisor', '감독자', 'field'),
('Pilih supervisor', 'Select supervisor', '감독자 선택', 'field'),
('AKTIF', 'ACTIVE', '활동적인', 'field'),
('NON AKTIF', 'NON ACTIVE', '비활성', 'field'),
('Non Debitur List', 'Non Debitur List', '부도 채권자 명단', 'field'),
('Hapus', 'Delete', '닦음', 'field'),
('url', 'Url', '균일 자원 식별자', 'field'),
('Masukkan url', 'Enter url', '균일 자원 식별자(URL)를 입력하십시오.', 'field'),
('Konfirmasi Hapus', 'Confirm Delete', '삭제 확인', 'field'),
('menghapus data ini?', 'delete this data?', '삭제하시겠습니까?', 'field'),
('Tanggal berakhir', 'End date', '만료일', 'field'),
('Tampilan Diagram', 'Diagram View', '다이어그램 보기', 'field'),
('data', 'data', '데이터', 'field'),
('breadcrumb', 'breadcrumb', '브레드크럼', 'field'),
('Halaman Belum Tersedia', 'Page Not Available', '페이지를 사용할 수 없습니다', 'field'),
('Umum', 'General', '일반', 'field'),
('Token core', 'Token core', '핵심 토큰', 'field'),
('Minimal skor', 'Minimal score', '최소 득점', 'field'),
('Form General', 'Form General', '일반 양식', 'field'),
('List Scoring', 'List Scoring', '리스트 스코어링', 'field'),
('Status Request', 'Status Request', '상태 요청', 'field'),
('PROCESS DONE', 'PROCESS DONE', '프로세스 완료', 'field'),
('SUBMITTED', 'SUBMITTED', '제출됨', 'field'),
('APPROVED', 'APPROVED', '승인됨', 'field'),
('Konfirmasi Pengajuan', 'Submit Confirmation', '제출 확인', 'field'),
('Konfirmasi Approve', 'Approve Confirmation', '승인 확인', 'field'),
('Konfirmasi Reject', 'Reject Confirmation', '거부 확인', 'field'),
('Konfirmasi Revisi', 'Revision Confirmation', '수정 확인', 'field'),
('Report slik result', 'Report slik result', '보고서 슬릭 결과', 'field'),
('Alasan', 'Reason', '이유', 'field'),
('Approval Variable', 'Approval Variable', '승인 변수', 'field'),
('Id App Request', 'Id App Request', '앱 ID 요청', 'field'),
('detail', 'details', '세부', 'field'),
('Debitur utama', 'Main debtor', '주요 채무자', 'field'),
('counter', 'counter', '카운터', 'field'),
('operator', 'operator', '운영자', 'field'),
('Pembaruan Terakhir', 'Last Update', '최종 업데이트', 'field'),
('No Ref Counter', 'No Ref Counter', '참고 카운터 없음', 'field'),
('Data Konsumen', 'Consumer Data', '소비자 데이터', 'field'),
('Status Pelamar', 'Status Applicant', '신청자 현황', 'field'),
('Jumlah Percobaan Ulang', 'Retry Count', '재시도 횟수', 'field'),
('Robot', 'Robot', '기계 인간', 'field'),
('Aktivitas Robot', 'Robot Activity', '로봇 활동', 'field'),
('MENUNGGU ANTRIAN', 'WAITING IN QUEUE', '줄 서서 기다리는 중', 'field'),
('PROSES PENGAJUAN', 'APPLICATION PROCESS', '지원 절차', 'field'),
('PENGAJUAN SELESAI', 'SUBMISSION COMPLETED', '제출 완료', 'field'),
('PENGAJUAN GAGAL', 'SUBMISSION FAILED', '제출 실패', 'field'),
('ANTRIAN PERSETUJUAN', 'APPROVAL QUEUE', '승인 대기열', 'field'),
('PERSETUJUAN SELESAI', 'AGREEMENT COMPLETED', '계약 완료', 'field'),
('PERSETUJUAN GAGAL', 'AGREEMENT FAILED', '합의가 결렬되었습니다', 'field'),
('ANTRIAN EKSTRAKSI', '', '', 'field'),
('EXTRAKSI SELESAI', 'EXTRACTION COMPLETE', '추출 완료', 'field'),
('EXTRAKSI GAGAL', 'EXTRACTION FAILED', '추출 실패', 'field'),
('PROSES ROBOT BERHASIL', 'ROBOT PROCESS', '로봇 프로세스 성공', 'field'),
('PROSES IDEB GAGAL', 'IDEB PROCESS FAILED', 'IDEB 프로세스가 실패했습니다', 'field'),
('PROSES IDEB SELESAI', 'IDEB PROCESS', 'IDEB 프로세스가', 'field'),
('IDEB PROCESS', 'IDEB PROCESS', 'IDEB 프로세스', 'field'),
('ANTRIAN PROSES IDEB', 'IDEB PROCESS QUEUE', 'IDEB 프로세스 큐', 'field'),
('PROSES SLIK GAGAL', 'SLIK PROCESS FAILED', 'SLIK 프로세스가 실패했습니다', 'field'),
('SLIK TIDAK DITEMUKAN', 'SLIK NOT FOUND', 'SLIK을 찾을 수 없습니다', 'field'),
('PROSES PENCARIAN SLIK', 'SLIK SEARCH PROCESS', 'SLIK 검색 프로세스 실패', 'field'),
('GAGAL', 'FAILED', '', 'field'),
('PROSES BERJALAN', 'PROCESS IN PROGRESS', '진행 중', 'field'),
('Status Distribusi', 'Distribution Status', '배포 상태', 'field'),
('Perbarui Tabel Permintaan', 'Update App Request Table', '앱 업데이트 요청 테이블', 'field'),
('Aplikasi', '', '', 'field'),
('Perbarui Aplikasi Distribusi', 'Update App Distribusi Table', 'Perbarui Aplikasi Distribusi', 'field'),
('Tabel', '', 'Tabel', 'field'),
('Pembaruan Robot', 'Update Robot', '업데이트 로봇', 'field'),
('Dedup', 'Dedup', '중복 제거', 'field'),
('Parameter User List', 'Parameter User List', '사용자 목록 매개변수', 'field'),
('REJECTED', 'REJECTED', '거부됨', 'field'),
('EXTRACT IDEB', 'EXTRACT IDEB', 'IDEB 추출', 'field'),
('PROSES SLIK', 'SLIK PROCESS', '슬릭 프로세스', 'field'),
('SUBMITED', 'SUBMITED', '제출됨', 'field'),
('PROSES SELESAI', 'DONE', '프로세스가 완료되었습니다', 'field'),
('ANTRIAN', 'QUEUE', '대기줄', 'field'),
('PROSES GAGAL', 'PROCESS FAILED', '프로세스가 실패했습니다', 'field'),
('Diagram Flow', 'Diagram Flow', '다이어그램 흐름', 'field'),
('PROSES EXTRAKSI', 'PROSES EXTRAKSI', '추출 과정', 'field'),
('PROSES IDEB', 'IDEB PROCESS', 'IDEB 프로세스', 'field'),
('Penanggung Jawab', 'PIC', '담당자', 'field'),
('Masukkan Penanggung', 'Enter PIC', '담당자 이름을', 'field'),
('Jawab', '', '입력하십시오.', 'field'),
('Syarat dan Ketentuan', 'Terms and Conditions', '약관', 'field'),
('Deskripsi', 'Description', '설명', 'field'),
('Edit Data Non Debitur', 'Edit Data Non Debitur', '비채무자 데이터 편집', 'field'),
('Tahap', 'Stage', '단계', 'field'),
('Mengajukan', 'Submit', '제출하다', 'field'),
('Setuju', 'Approve', '승인하다', 'field'),
('melakukan pengajuan', 'submit this data?', '제출하시겠어요?', 'field'),
('terhadap data ini?', '', '', 'field'),
('Konfirmasi Simpan', 'Save Confirmation', '저장 확인', 'field'),
('Apakah anda yakin ingin', 'Are you sure you want to', '이 데이터를', 'field'),
('menyimpan data ini?', 'save this data?', '저장하시겠어요?', 'field'),
('Detail Approval', '', '세부 승인', 'field'),
('Pengajuan', 'Submission', '제출', 'field'),
('Segment', 'Segment', '분절', 'field'),
('Pilih Segment', 'Select Segment', '세그먼트를 선택하세요', 'field'),
('Umur', 'Age', '나이', 'field'),
('Masukkan Umur', 'Enter Age', '나이 입력', 'field'),
('Bulan', 'Month', '월', 'field'),
('Masukkan Bulan', 'Enter Month', '월을 입력하세요', 'field'),
('Email', 'Email', '이메일', 'field'),
('Masukkan Email', 'Enter Email', '이메일을 입력하세요', 'field'),
('Data Pekerjaan', 'Job Data', '직무 데이터', 'field'),
('Pekerjaan', 'Job', '일하다', 'field'),
('Pilih Pekerjaan', 'Select a Job', '직업을 선택하세요', 'field'),
('NIP', 'NIP', '집게발', 'field'),
('Masukkan NIP', 'Enter NIP', 'NIP 입력', 'field'),
('Tempat Kerja', 'Workplace', '직장', 'field'),
('Masukkan Tempat Kerja', 'Enter Workplace', '직장에 들어가기', 'field'),
('Umur Pensiun', 'Retirement Age', '은퇴 연령', 'field'),
('Masukkan Umur Pensiun', 'Enter Retirement Age', '은퇴 연령에 진입', 'field'),
('Pensiun Bulan Ke', 'Retirement Month', '은퇴의 달', 'field'),
('Masukkan Pensiun Bulan Ke', 'Enter Monthly Retirement', '월별 퇴직금 입력', 'field'),
('Nama Tempat Kerja', 'Name of Workplace', '직장명', 'field'),
('Masukkan Nama Tempat', 'Enter Workplace Name', '직장 이름을 입력하세요', 'field'),
('Kerja', '', '', 'field'),
('Telepon Kantor', 'Office Phone', '사무실 전화', 'field'),
('Masukkan Telepon Kantor', 'Enter Office Phone', '사무실 전화번호를 입력하세요', 'field'),
('Jabatan', 'Job Title', '직책', 'field'),
('Masukkan Jabatan', 'Enter Job Title', '위치를 입력하세요', 'field'),
('Nomor Tabungan Pencairan', 'Credit Disbursement', '신용 지급 저축 번호', 'field'),
('Kredit', 'Savings Number', '', 'field'),
('Masukkan Nomor Tabungan', 'Enter Credit Disbursement', '신용 지급 저축 번호를', 'field'),
('Pencairan Kredit', 'Savings Number', '입력하세요', 'field'),
('Nomor Rekening Gaji', 'Salary Account Number', '급여 계좌 번호', 'field'),
('Masukkan Nomor Rekening', 'Enter Salary Account', '급여 계좌 번호를', 'field'),
('Gaji', 'Number', '입력하세요', 'field'),
('Cara Pembayaran Gaji', 'Salary Payment Method', '급여 지급 방식', 'field'),
('Pilih Cara Pembayaran Gaji', 'Select Salary Payment', '급여 지급 방식을', 'field'),
('Gaji Pokok', 'Basic salary', '기본급', 'field'),
('Masukkan Gaji Pokok', 'Enter Basic Salary', '기본 급여를 입력하세요', 'field'),
('Tunjangan Suami Istri', 'Spousal Allowance', '배우자 수당', 'field'),
('Masukkan Tunjangan Suami', 'Enter Spousal Allowance', '배우자 부양비를', 'field'),
('Istri', '', '입력하세요', 'field'),
('Tunjangan Anak', 'Child Support', '자녀 양육비', 'field'),
('Masukkan Tunjangan Anak', 'Enter Child Allowance', '아동 수당을 입력하세요', 'field'),
('Tunjangan Beras', 'Rice Allowance', '쌀 수당', 'field'),
('Masukkan Tunjangan Beras', 'Enter Rice Allowance', '쌀 배급량을 입력하세요', 'field'),
('Tunjangan Jabatan', 'Structural Position', '구조적 위치 허용 오차', 'field'),
('Struktural', 'Allowance', '', 'field'),
('Masukkan Tunjangan', 'Enter Structural Position', '구조적 위치 허용값을', 'field'),
('Jabatan Struktural', 'Allowance', '입력하십시오.', 'field'),
('Tunjangan Posisi', 'Functional Position', '직무 위치 수당', 'field'),
('Fungsional', 'Allowance', '', 'field'),
('Masukkan Tunjangan Posisi', 'Enter Functional Position', '기능별 직위 수당을', 'field'),
('Tunjangan Umum', 'General Allowance', '일반 수당', 'field'),
('Tunjangan Lain Lain', 'Other Allowances', '기타 수당', 'field'),
('Masukkan Tunjangan Lain', 'Enter Other Allowances', '기타 수당을 입력하세요', 'field'),
('Lain', '', '', 'field'),
('Askes Bersih', 'Clean Health Insurance', '클린 헬스 인슈어런스', 'field'),
('Masukkan Askes Bersih', 'Enter Clean Health', '깨끗한 질문을 입력하세요', 'field'),
('Pembulatan', 'Rounding', '반올림', 'field'),
('Masukkan Pembulatan', 'Enter Rounding', '반올림 입력', 'field'),
('Total Pendapatan', 'Total Revenue', '총 수익', 'field'),
('PFK Beras', 'Rice PFK', '쌀 PFK', 'field'),
('Masukkan PFK Beras', 'Enter PFK Rice', 'PFK 라이스를 입력하세요', 'field'),
('Simpanan Wajib', 'Mandatory Savings', '의무 저축', 'field'),
('Masukkan Simpanan Wajib', 'Enter Mandatory Savings', '의무 저축액을 입력하세요', 'field'),
('Sewa Rumah', 'Rent a house', '집을 임대하세요', 'field'),
('Masukkan Biaya Sewa', 'Enter House Rent Cost', '집세 입력', 'field'),
('Rumah', '', '', 'field'),
('Tabungan Rumah PNS', 'Civil Servant Home Savings', '공무원 주택저축', 'field'),
('Masukkan Tabungan Rumah', 'Enter Civil Servant Home', '공무원 주택저축 계좌에', 'field'),
('PNS', 'Savings', '가입하세요', 'field'),
('Hutang Kelebihan', 'Excess Debt', '과도한 부채', 'field'),
('Masukkan Hutang', 'Enter Excess Debt', '초과 부채를 입력하세요', 'field'),
('Kelebihan', '', '', 'field'),
('Lain Lain', 'Etc', '등', 'field'),
('Masukkan Biaya Lain Lain', 'Enter Other Costs', '기타 비용을 입력하세요', 'field'),
('Pajak Penghasilan', 'Income tax', '소득세', 'field'),
('Masukkan Pajak', 'Enter Income Tax', '소득세를 입력하세요', 'field'),
('Penghasilan', '', '', 'field'),
('Askes Potongan', 'Discounted Health', '할인된 건강 보험', 'field'),
('Masukkan Askes Potongan', 'Enter Discounted Health', '할인 요청 입력', 'field'),
('Total Potongan', 'Total Deductions', '총 공제액', 'field'),
('Masukkan Total Potongan', 'Enter Total Deductions', '총 공제액을 입력하세요', 'field'),
('Total Gaji Bersih', 'Total Net Salary', '총 순수 급여', 'field'),
('Tunjangan TKD TPP', 'TKD TPP Allowance', 'TKD TPP 허용량', 'field'),
('Masukkan Tunjangan TKD', 'Enter TKD TPP Allowance', 'TKD TPP 허용량을', 'field'),
('TPP', '', '입력하세요', 'field'),
('Tunjangan Lain', 'Other Allowances', '기타 수당', 'field'),
('Total Tunjangan Lain', 'Total Other Allowances', '기타 수당 총액', 'field'),
('Tunjangan Lain Di Luar Gaji', 'Other Allowances Outside', '채무자의 순 급여 외 기타', 'field'),
('Bersih Debitur', 'of the Debtor''s Net Salary', '수당', 'field'),
('Penghasilan Keluarga', 'Other Family Income', '기타 가족 소득', 'field'),
('Lainnya', '', '', 'field'),
('Penghasilan Lainnya', 'Other Income', '기타 소득', 'field'),
('Masukkan Penghasilan', 'Enter Other Income', '기타 소득을 입력하세요', 'field'),
('Jumlah Keseluruhan', 'Total salary amount', '총 급여 금액', 'field'),
('Data Fasilitas', 'Facility Data', '시설 데이터', 'field'),
('Fasilitas Kredit', 'Credit Facilities', '신용 시설', 'field'),
('Ringkasan', 'Summary', '요약', 'field'),
('ID Fasilitas', 'Facility ID', '시설 ID', 'field'),
('Jenis Kredit yang', 'Type of Credit Required', '필요한 학점 종류', 'field'),
('dibutuhkan', '', '', 'field'),
('Pilih Jenis Kredit yang', 'Select the type of credit', '필요한 학점 유형을', 'field'),
('Jenis Pengajuan', 'Submission Type', '제출 유형', 'field'),
('Pilih Jenis Pengajuan', 'Select Submission Type', '제출 유형을 선택하세요', 'field'),
('Palfon Kredit yang Diminta', 'Requested Credit Ceiling', '요청된 신용 한도', 'field'),
('Masukkan Plafon Kredit', 'Enter the requested credit', '요청하신 신용 한도를', 'field'),
('yang Diminta', 'limit', '입력하세요.', 'field'),
('Produk Kredit yang', 'Required Credit Products', '필수 신용 상품', 'field'),
('Dibutuhkan', '', '', 'field'),
('Pilih Produk Kredit yang', 'Select the required credit', '필요한 신용 상품을', 'field'),
('Blokir Angsuran', 'Installment Block', '할부 블록', 'field'),
('Pilih Blokir Angsuran', 'Select Block Installment', '분할 납부 방식을 선택하세요', 'field'),
('Tujuan Penggunaan SID', 'Purpose of Using SID', 'SID 사용 목적', 'field'),
('Pilih Tujuan Penggunaan', 'Select the Purpose of Using', 'SID 사용 목적을', 'field'),
('SID', 'SID', '선택하세요', 'field'),
('Tujuan Penggunaan LBU', 'Purpose of Using LBU', 'LBU 사용 목적', 'field'),
('LBU', 'LBU', '선택하세요', 'field'),
('Jangka Waktu yang Diminta', 'Requested Timeframe', '요청된 기간', 'field'),
('Masukkan Jangka Waktu', 'Enter the requested time', '원하는 기간을 입력하세요', 'field'),
('Jenis Bunga', 'Type of Interest', '대출 이자 유형', 'field'),
('Pilih Jenis Bunga', 'Select Interest', '대출 이자 유형을 선택하세요', 'field'),
('Suku Bunga Efektif', 'Effective Interest Rate', '실효이자율', 'field'),
('Masukkan Suku Bunga', 'Enter Effective Interest Rate', '실효이자율을 입력하세요', 'field'),
('Efektif', '', '', 'field'),
('Kredit Selesai', 'Credit Completed', '학점 이수 완료', 'field'),
('Masukkan Kredit Selesai', 'Enter Credit Completed', '학점 입력 완료', 'field'),
('Angsuran', 'Installments', '할부', 'field'),
('Masukkan Angsuran', 'Enter Installment', '할부 입력', 'field'),
('Gaji Debitur', 'Debtor''s Salary', '채무자의 급여', 'field'),
('Persen THP', 'THP Percentage', 'THP 비율', 'field'),
('Sisa Gaji Bersih yang', 'Net Salary Remaining', '남은 순수 급여', 'field'),
('diterima (setelah dipotong', '', '', 'field'),
('angsuran kredit)', '', '', 'field'),
('Penghasilan Keluarga Diluar', 'Family Income Excluding', '가족 소득 (소득 제외)', 'field'),
('Gaji Debitur + Penghasilan', 'Debtor''s Salary + Family', '채무자의 급여 + 가족 소득', 'field'),
('Keluarga', 'Income', '', 'field'),
('Angsuran Kredit Tidak', 'Unpaid Credit Installments', '미납 신용 할부금', 'field'),
('Dilunasi', '', '', 'field'),
('Total Angsuran', 'Total Installment', '총 할부금', 'field'),
('Penghasilan Keluarga -', 'Family Income - Credit', '가족 소득 - 대출 분할 상환', 'field'),
('Angsuran Kredit', 'Installments', '', 'field'),
('Blokir Angsuran Pra', 'Block Pre-Retirement', '퇴직 전 분할 납부', 'field'),
('Purnabakti', 'Installments', '', 'field'),
('Sisa Diterima', 'Remainder Received', '나머지 금액 수령', 'field'),
('Pelunasan Pinjaman Lama', 'Old Loan Repayment', '기존 대출금 상환', 'field'),
('Jumlah Bulan Sebelum', 'Number of Months Before', '은퇴까지 남은 개월 수', 'field'),
('Pensiun', 'Retirement', '', 'field'),
('Jenis Kredit', 'Type of Credit', '신용 유형', 'field'),
('Pilih Jenis Kredit', 'Select Credit Type', '신용 유형을 선택하세요', 'field'),
('Nomor Perjanjian Kredit', 'Credit Agreement Number', '신용 계약 번호', 'field'),
('Masukkan Nomor', 'Enter Credit Agreement', '신용 계약 번호를', 'field'),
('Perjanjian', 'Number', '입력하세요', 'field'),
('Tanggal Perjanjian Kredit', 'Credit Agreement Date', '신용 계약일', 'field'),
('Nomor Rekening', 'Account number', '계좌번호', 'field'),
('Kolektabilitas', 'Collectibility', '수집 가능성', 'field'),
('Masukkan Kolektabilitas', 'Enter Collectability', '수집 가능성에 참여하세요', 'field'),
('Status Rekening', 'Account Status', '계정 상태', 'field'),
('Pilih Status Rekening', 'Select Account Status', '계정 상태를 선택하세요', 'field'),
('Plafon', 'Loan Limit', '대출 한도', 'field'),
('Masukkan Plafon', 'Enter Loan Limit', '대출 한도를 입력하세요', 'field'),
('Fasilitas Kredit Existing', '', '', 'field'),
('External', '', '', 'field'),
('Debitur', 'Debtor', '채무자', 'field'),
('Tenor', 'Tenor', '테너', 'field'),
('Masukkan Tenor', 'Enter Tenor', '테너를 입력하세요', 'field'),
('Baki Debit', 'Debit Balance', '차변 잔액', 'field'),
('Masukkan Baki Debit', 'Enter Debit Balance', '직불 카드 트레이에 입력하세요', 'field'),
('Angsuran Pokok', 'Principal Installment', '원금 할부금', 'field'),
('Masukkan Angsuran Pokok', 'Enter Principal Installment', '원금 납부액을 입력하세요', 'field'),
('Angsuran Bunga', 'Interest Installment', '이자 할부', 'field'),
('Masukkan Angsuran Bunga', 'Enter Interest Installment', '이자 할부 금액을 입력하세요', 'field'),
('Masukkan Total Angsuran', 'Enter Total Installment', '총 할부금을 입력하세요', 'field'),
('Bunga Berjalan', 'floating interest rate', '변동금리', 'field'),
('Masukkan Bunga Berjalan', 'Enter floating interest rate', '변동금리를 입력하세요', 'field'),
('Tunggakan Pokok', 'Principal Arrears', '원금 연체금', 'field'),
('Masukkan Tunggakan Pokok', 'Enter Principal Arrears', '원금 연체금을 입력하세요', 'field'),
('Tunggakan Bunga', 'Interest Arrears', '이자 연체', 'field'),
('Masukkan Tunggakan', 'Enter Interest Arrears', '이자 연체액을 입력하세요', 'field'),
('Bunga', '', '', 'field'),
('Penalti', 'Penalty', '패널티', 'field'),
('Masukkan Penalti', 'Enter Penalty', '벌칙 입력', 'field'),
('Akan Dilunasi', 'Will be paid off', '상환될 것입니다', 'field'),
('Bank', 'Bank', '은행', 'field'),
('Pilih Bank', 'Select Bank', '셀렉트 뱅크', 'field'),
('Penyebab Deviasi', 'Causes of Deviation', '편차의 원인', 'field'),
('Keterangan Deviasi', 'Deviation Description', '편차 설명', 'field'),
('Detail slik resultd', 'Detail slik result', 'SLIK 조회 결과 상세', 'field'),
('Total fasilitas', 'Total', '총 시설 수', 'field'),
('Nama Pasangan', 'Partner''s Name', '파트너 이름', 'field'),
('Masukkan Nama Pasangan', 'Enter Partner Name', '파트너 이름을 입력하세요', 'field'),
('Kontrak fasilitas aktif', 'Active Facilitie Contract', '활성 금융시설 계약', 'field'),
('Internal', 'Facilities', '', 'field'),
('Total fasilitas aktif', 'Total Active Facilities', '총 활성 금융시설', 'field'),
('Platfon efective', 'Efectif credit limit', '유효 신용한도', 'field'),
('Policy result', 'Policy result', '정책 결과', 'field'),
('Kontrak fasilitas lunas', 'Settled Facility Contract', '상환 완료 금융시설 계약', 'field'),
('Kontrak fasilitas lain lain', 'Other Facility Contract', '기타 금융시설 계약', 'field'),
('Master Produk', 'Master Product', '마스터 제품', 'field'),
('Kontrak fasilitas hapus', 'Written-off Facility', '상각 금융시설 계약', 'field'),
('buku', 'Contract', '', 'field'),
('Deviasi', 'Deviation', '편차', 'field'),
('Konfirmasi Export PDF', 'PDF Export Confirmation', 'PDF 내보내기 확인', 'field'),
('melakukan export data', 'export the data as a PDF?', '내보내시겠습니까?', 'field'),
('dalam bentuk PDF?', '', '', 'field'),
('Konfirmasi Export TXT', 'TXT Export Confirmation', 'TXT 내보내기 확인', 'field'),
('Apakah Anda yakin ingin', 'Are you sure you want to', '데이터를 TXT 형식으로', 'field'),
('mengekspor data dalam', 'export the data as a TXT', '내보내시겠습니까?', 'field'),
('format TXT?', 'file?', '', 'field'),
('Export pdf', 'Export PDF', 'PDF 내보내기', 'field'),
('Export TXT', 'Export TXT', 'TXT 내보내기', 'field'),
('Nama Produk', 'Product name', '제품명', 'field'),
('kesimpulan', 'Conclusion', '결론', 'field'),
('Masukkan Nama Produk', 'Enter Product Name', '제품명을 입력하세요', 'field'),
('Masukkan Deskripsi', 'Enter Description', '설명을 입력하세요', 'field'),
('Tanggal berlaku', 'Effective Date', '시행일', 'field'),
('Tanggal Kedaluwarsa', 'Expiry Date', '만료일', 'field'),
('Kriteria Nasabah', 'Customer Criteria', '고객 기준', 'field'),
('Minimal Umur', 'Minimum Age', '최소 연령', 'field'),
('Pengaturan Fasilitas', 'Facility Setting', '시설 설정', 'field'),
('Minimal Plafon', 'Minimal Plafon', '대출 최저 한도', 'field'),
('Masukkan Minimal Plafon', 'Enter Minimal Plafon', '대출 대출 한도를 입력하세요', 'field'),
('Setoran Awal Minimum', 'Minimum Initial Deposit', '최소 초기 예치금', 'field'),
('Masukkan Setoran Awal', 'Enter Minimum Initial', '최소 초기 예치금을', 'field'),
('Minimum', 'Deposit', '입력하세요', 'field'),
('Minimal Tenor', 'Minimal Tenor', '미니멀 테너', 'field'),
('Maximal Tenor', 'Maximal Tenor', '최대 테너', 'field'),
('Masukkan Maximal Tenor', 'Enter the maximum tenor', '최대 테너를 입력하세요', 'field'),
('Promo Bunga Spesial', 'Promo Interest', '프로모션 관심', 'field'),
('Masukkan Promo Bunga', 'Enter Promo Interest', '특별 관심 분야 프로모션에', 'field'),
('Spesial', '', '참여하세요', 'field'),
('Promo Period', 'Promo Period', '프로모션 기간', 'field'),
('Masukkan Promo Period', 'Enter Promo Period', '프로모션 기간 참여하기', 'field'),
('Spesifikasi Objek', 'Object Specification', '객체 명세', 'field'),
('Dokumen Jaminan', 'Collateral Document', '담보 서류', 'field'),
('Pengaturan Jaminan', 'Collateral Setting', '담보 설정', 'field'),
('Masukkan Kode Produk', 'Enter Product Code', '제품 코드를 입력하세요', 'field'),
('Versi', 'Version', '버전', 'field'),
('Deviasi Konsumer', 'Consumer Deviation', '소비자 편차', 'field'),
('Deviasi Komersil', 'Commercial Deviation', '상업적 편차', 'field'),
('Dokumen Daftar Periksa', 'Checklist Document', '체크리스트 문서', 'field'),
('Masukkan Minimal Umur', 'Enter Minimum Age', '최소 연령을 입력하세요', 'field'),
('Maksimal Umur', 'Maximum Age', '최대 연령', 'field'),
('Masukkan Maksimal Umur', 'Enter Maximum Age', '최대 연령을 입력하세요', 'field'),
('Jenis Tempat Pekerjaan', 'Occupation Type', '직업 유형', 'field'),
('Pilih Jenis Tempat Pekerjaan', 'Select Occupation Type', '직업 유형을 선택하세요', 'field'),
('Status Karyawan', 'Employee Status', '직원 상태', 'field'),
('Pilih Status Karyawan', 'Select Employee Status', '직원 상태를 선택하세요', 'field'),
('Periode Kerja Minimum', 'Minimum Work Period', '최소 근무 기간', 'field'),
('Masukkan Periode Kerja', 'Enter Minimum Work Period', '최소 근무 기간을', 'field'),
('Minimal Pendapatan', 'Minimum Income', '최저 소득', 'field'),
('Masukkan Minimal', 'Enter Minimum Income', '최소 소득을 입력하세요', 'field'),
('Pendapatan', '', '', 'field'),
('Tipe Dokumen Fasilitas', 'Facility Document Type', '시설 문서 유형', 'field'),
('Wajib', 'Mandatory', '필수적인', 'field'),
('Tarif Bertingkat', 'Tiered Rate', '단계별 요금', 'field'),
('Skema Bunga', 'Interest Schema', '관심 계획', 'field'),
('Pilih Skema Bunga', 'Select Interest Schema', '관심 분야 선택', 'field'),
('Regular Promo', 'Regular Promo', '일반 프로모션', 'field'),
('Flat Anuitas', 'Flat Annuity', '정액 연금', 'field'),
('Anuitas', 'Annuity', '연금', 'field'),
('Masukkan Minimal Tenor', 'Enter Minimum Tenor', '최소 테너를 입력하세요', 'field'),
('Masukkan Flat Anuitas', 'Enter Flat Annuity', '정액 연금 상품에 가입하세요', 'field'),
('Bunga Promosi', 'Promo Interest', '프로모션 관심', 'field'),
('Masukkan Bunga Promosi', 'Enter Promo Interest', '프로모션 관심 분야를 입력하세요', 'field'),
('Periode Promosi', 'Promo Period', '프로모션 기간', 'field'),
('Masukkan Periode Promosi', 'Enter Promo Period', '프로모션 기간 참여하기', 'field'),
('Maximal Plafon', 'Maximal Plafon', '막시말 플라폰', 'field'),
('Masukkan Maximal Plafon', 'Enter Maximal Plafon', '최대 천장을 입력하세요', 'field'),
('Konfigurasi Biaya', 'Fee Configuration', '수수료 구성', 'field'),
('Robot Slik', 'Robot Slik', '슬릭 로봇', 'field'),
('Masukkan URL', 'Enter URL', 'URL을 입력하세요', 'field'),
('URL Stream', 'URL Stream', '스트림 URL', 'field'),
('Masukkan URL Stream', 'Enter Stream URL', '스트림 URL을 입력하세요', 'field'),
('URL VNC', 'URL VNC', 'URL VNC', 'field'),
('Masukkan URL VNC', 'Enter URL VNC', 'VNC URL을 입력하세요', 'field'),
('Pembuatan Dokumen', 'Document Creation', '문서 작성', 'field'),
('Kriteria nasabah', 'Customer criteria', '고객 기준', 'field'),
('Parameter general', 'General parameters', '일반 매개변수', 'field'),
('Spesifikasi objek', 'Object specification', '객체 사양', 'field'),
('Inquiry pengajuan', 'Application inquiry', '신청 조회', 'field'),
('Fasilitas Kredit Internal', 'Fasilitas Kredit Existing', 'Fasilitas 신용 기존 내부', 'field'),
('Pengajuan Detail', 'Submission Details', '제출 세부 정보', 'field'),
('Pelunasan', 'Settlement', '합의', 'field'),
('Skema bunga', 'Interest schema', '이자 방식', 'field'),
('regular/promo', 'regular/promo', '일반 / 프로모션', 'field'),
('Minimal plafon', 'Minimal plafon', '최소 한도', 'field'),
('Masukkan Pelunasan', 'Enter Settlement', '', 'field'),
('Masukkan minimal plafon', 'Enter minimal plafon', '최소 한도를 입력하세요', 'field'),
('Maximal plafon', 'Maximal plafon', '최대 한도', 'field'),
('Minimum Setoran Awal', 'Minimum initial deposit', '최소 초기 예치금', 'field'),
('Masukkan setoran awal', 'Enter minimum initial', '최소 초기 예치금을', 'field'),
('Keterangan Biaya', 'Cost Description', '비용 설명', 'field'),
('Minimal tenor', 'Minimum tenor', '최소 대출 기간', 'field'),
('Masukkan minimal tenor', 'Enter minimum tenor', '최소 대출 기간을 입력하세요', 'field'),
('Persentase', 'Percentage', '백분율', 'field'),
('Maksimal tenor', 'Maximal tenor', '최대 대출 기간', 'field'),
('Masukkan maksimal tenor', 'Enter maximal tenor', '최대 대출 기간을 입력하세요', 'field'),
('Nominal Biaya', 'Fee Amount', '수수료 금액', 'field'),
('Masukkan Nominal Biaya', 'Enter Fee Amount', '수수료 금액을 입력하세요', 'field'),
('Dengan agunan / tanpa', 'secured/unsecured', '담보 / 무담보', 'field'),
('agunan', '', '', 'field'),
('Biaya', 'Fee', '수수료', 'field'),
('Masukkan Biaya', 'Enter Fee', '수수료를 입력하세요', 'field'),
('Pilih dengan agunan / tanpa', 'Enter secure/unsecure', '담보/무담보를 선택하세요', 'field'),
('Suku bunga bertingkat', 'Tiered rate', '단계별 금리', 'field'),
('Masukkan Penyebab', 'Enter Deviation Reason', '편차 사유를 입력하세요', 'field'),
('Deviasiat', '', '', 'field'),
('Flat anuitas', 'Flat annuity', '고정금리 원리금균등상환', 'field'),
('anuitas', 'annuity', '원리금 균등상환', 'field'),
('Tanggal Dibuat', 'Created Date', '생성일', 'field'),
('Dibuat Oleh', 'Created By', '생성자', 'field'),
('Pilih regular promo', 'Select regular promo', '일반/프로모션을 선택하세요', 'field'),
('Masukkan anuitas', 'Enter annuity', '원리금 균등상환을 입력하세요', 'field'),
('Tipe bunga', 'Interest type', '금리 유형', 'field'),
('Objek spesifikasi', 'Object specification', '객체 사양', 'field'),
('Tipe jaminan', 'Collateral type', '담보 유형', 'field'),
('Objek jaminan', 'Collateral objek', '담보 대상', 'field'),
('Pilih tipe jaminan', 'Select type collateral', '담보 유형을 선택하세요', 'field'),
('Deskripsi Pihak Terkait', 'Description Related Parties', '관련 당사자 설명', 'field'),
('Masukkan Deskripsi Pihak', 'Enter Description of', '관련 당사자 설명을', 'field'),
('Terkait', 'Related Parties', '입력하세요', 'field'),
('Data Partner', 'Partner Data', '파트너 정보', 'field'),
('Link Jaminan', 'Collateral Link', '담보 연결', 'field'),
('Tipe Jaminan Fasilitas', 'Facility Collateral Type', '시설 담보 유형', 'field'),
('Pilih Tipe Jaminan Fasilitas', 'Select Facility Collateral', '시설 담보 유형을', 'field'),
('Tipe Dokumen Jaminan', 'Collateral Document Type', '담보 서류 유형', 'field'),
('Pilih Tipe Dokumen Jaminan', 'Select Collateral Document', '담보 서류 유형을', 'field'),
('Kepemilikan Jaminan', 'Facility Collateral', '시설 담보 소유권', 'field'),
('Fasilitas', 'Ownership', '', 'field'),
('Data Kepemilikan Jaminan', 'Collateral Ownership Data', '담보 소유 정보', 'field'),
('Nomor Identitas', 'Collateral Ownership', '담보 소유자 신분증 번호', 'field'),
('Masukkan Nomor Identitas', 'Enter Collateral Ownership', '담보 소유자 신분증 번호를', 'field'),
('Nama Kepemilikan Jaminan', 'Collateral Owner Name', '담보 소유자 이름', 'field'),
('Masukkan Nama', 'Enter Collateral Owner', '담보 소유자 이름을', 'field'),
('Objek Jaminan', 'Collateral Object', '담보 대상', 'field'),
('Masukkan Objek Jaminan', 'Enter Collateral Object', '담보 대상을 입력하세요', 'field'),
('Draft Pengajuan', '', '', 'field'),
('Pengajuan Baru', 'New Application', '신규 신청', 'field'),
('Alamat KTP', 'ID Card Address', '신분증 주소', 'field'),
('Kode Pos', 'ZIP Code', '우편번호', 'field'),
('Tanggal devias', 'Deviation date', '일탈일자', 'field'),
('Deviasi oleh', 'Deviation by', '일탈자', 'field'),
('Produk Credit', 'Credit product', '여신상품', 'field'),
('Platfon credit', 'Credit limit', '여신한도', 'field'),
('Jenis bunga', 'Interest type', '금리 유형', 'field'),
('Proses akad kredit', 'Loan Agreement Process', '대출 약정 절차', 'field'),
('Data Tambahan', 'Additional Data', '추가 데이터', 'field'),
('Tanggal sk direksi', 'Board of Directors Decree', '이사회 결의서 날짜', 'field'),
('Pasal untuk addendum', 'Article for addendum', '부속합의서 조항', 'field'),
('Masukkan pasal untuk', 'Enter article for addendum', '부속합의서 조항 입력', 'field'),
('addendum', '', '', 'field'),
('Ayat untuk addendum', 'Paragraph for addendum', '부속합의서 항', 'field'),
('Masukkan ayat untuk', 'Enter paragraph for', '부속합의서 항 입력', 'field'),
('Bunyi ayat', 'Paragraph content', '조항 내용', 'field'),
('Masukkan bunyi ayat', 'Enter paragraph content', '조항 내용 입력', 'field'),
('Domisili kantor panitera', 'Domicile of the District', '지방법원 서기관 사무실', 'field'),
('pengadilan negeri', 'Court Registrar''s Office', '소재지', 'field'),
('Nomor sk direksi', 'Board of Directors Decree', '이사회 결정 번호', 'field'),
('Masukkan domisili kantor', 'Enter the Domicile of the', '지방법원 서기관 사무실', 'field'),
('panitera pengadilan negeri', 'District Court Registrar''s', '소재지를 입력하세요', 'field'),
('Masukkan nomor sk direksi', 'Enter the Board of Directors', '이사회 결정 번호를', 'field'),
('Biaya perolehan', 'Acquisition Cost', '취득 비용', 'field'),
('Masukkan biaya perolehan', 'Enter the Acquisition Cost', '취득 비용을 입력하세요', 'field'),
('Pilih tipe bunga', 'Select interest type', '이자 유형을 선택하세요', 'field'),
('Masa tenggang pokok', 'Principal Grace Period', '원금 거치 기간', 'field'),
('Masukkan masa tenggang', 'Enter principak grace', '원금 거치 기간을', 'field'),
('pokok', 'period', '입력하세요', 'field'),
('Masa tunda bunga', 'Interest grace period', '이자 거치 기간', 'field'),
('Masukkan masa tunda', 'Enter interest grace period', '이자 거치 기간을', 'field'),
('bunga', '', '입력하세요', 'field'),
('Distr. Tunda bunga', 'Interest Grace Period', '이자 거치 기간 분배', 'field'),
('Masukkan distr. Tunda', 'Enter interest grace period', '이자 거치 기간 분배를', 'field'),
('Pembayaran via', 'Payment method', '결제 방법', 'field'),
('Pilih pembayaran via', 'Select payment method', '결제 방법을 선택하세요', 'field'),
('Tanggal pembayaran', 'Payment date', '지급일', 'field'),
('Masukkan tanggal', 'Enter payment date', '지급일을 입력하세요', 'field'),
('pembayaran', '', '', 'field'),
('Tanggal pemblokiran afiliasi', 'Affiliate Blocking Date', '제휴 차단일', 'field'),
('pemblokiran afiliasi', '', '', 'field'),
('Menggunakan asuransi', 'Use insurance', '보험 사용', 'field'),
('Pilih menggunakan asuransi', 'Pilih menggunakan', '보험 사용 여부를', 'field'),
('Catatan', 'note', '비고', 'field'),
('Masukkan catatan', 'Enter note', '비고를 입력하세요', 'field'),
('referal', 'referral', '추천 경로', 'field'),
('Masukkan referal', 'Enter referral', '추천 경로를 선택하세요', 'field'),
('Status sindikasi', 'Syndication status', '신디케이션 상태', 'field'),
('Peran sindikasi', 'Syndication role', '신디케이션 역할', 'field'),
('Pilih peran sindikasi', 'Select syndication role', '', 'field'),
('Data asuransi', 'Insurance information', '보험 정보', 'field'),
('Premi', 'Premi', '보험료', 'field'),
('Perusahaan asuransi', 'Insurance company', '보험회사', 'field'),
('Contact person', 'Contact person', '담당자', 'field'),
('Tanggal jatuh tempo', 'Due Date', '만기일', 'field'),
('Tambah asuransi', 'Add insurance', '보험 추가', 'field'),
('Id fasilitas', 'Facility id', '시설 ID', 'field'),
('Asuransi', 'Insurance', '보험', 'field'),
('Nomor polis', 'Police number', '보험증권 번호', 'field'),
('Vendor', 'Vendor', '공급업체', 'field'),
('Data pencairan kredit', 'Loan Disbursement', '대출 실행 정보', 'field'),
('cif', 'cif', 'cif', 'field'),
('Metode pencairan', 'Disbursement Method', '대출 실행 방식', 'field'),
('Masukkan cif', 'Enter cif', 'CIF를 입력하세요', 'field'),
('Masukkan jatuh tempo', 'Enter due date', '납부 기한일을 입력하세요', 'field'),
('Jenis perjanjian kredit', 'Credit agreement type', '대출 약정 유형', 'field'),
('Pilih jenis perjanjian kredit', 'Select credit agreement', '', 'field'),
('No rekening afiliasi', 'Affiliate account number', '제휴 계좌 번호', 'field'),
('Pilih no rekening afiliasi', 'Select affiliate account', '제휴 계좌 번호를', 'field'),
('No rekening', 'Account number', '계좌 번호', 'field'),
('No. pk', 'Credit agreement number', '대출 약정 번호', 'field'),
('Masukkan no. pk', 'Enter credit agreement', '대출 약정 번호를', 'field'),
('No. SPPK', 'Credit Approval Letter', '대출 승인서 번호', 'field'),
('Upload dokumen', 'Upload document', '문서 업로드', 'field'),
('Data pencairan', 'Disbursement information', '실행 정보', 'field'),
('Biaya-biaya', 'Fee / costs', '수수료 / 비용', 'field'),
('Keterangan biaya', 'Fee description', '수수료 설명', 'field'),
('Persen', 'Percent', '퍼센트', 'field'),
('Nominal biaya', 'Fee amount', '수수료 금액', 'field'),
('persentase', 'percentage', '백분율', 'field'),
('Data akad kredit', 'Credit agreement', '대출 약정 정보', 'field'),
('Data debitur', 'Data debitur', '차주 정보', 'field'),
('Alamat domisili', 'Residential address', '거주지 주소', 'field'),
('Nama panggilan', 'Nickname', '별명', 'field'),
('Pihak terkaitd', 'Relate parties', '관련 당사자', 'field'),
('data pasangan', 'Spouse information', '배우자 정보', 'field'),
('Jumlah tanggungan anak', 'Number of dependent', '부양 자녀 수', 'field'),
('Alamat sesuai ktp', 'Address as per id card', '신분증 기재 주소', 'field'),
('Data kerabat', 'Relative information', '친족 정보', 'field'),
('Hubungan', 'Relationship', '관계', 'field'),
('Pensiun bulan ke', 'Retirement month', '퇴직 월', 'field'),
('Pendapatan gaji bersih', 'Borrower’s Net Salary', '차주의 순급여 소득', 'field'),
('debitur', 'Income', '', 'field'),
('Potongan gaji bersih debitur', 'Borrower’s Net Salary', '차주의 순급여 공제액', 'field'),
('Dokumen cheklist', 'Document checklist', '문서 체크리스트', 'field'),
('Terunggah', 'Uploaded', '업로드됨', 'field'),
('Tipe dokumen', 'Document Type', '문서 유형', 'field'),
('Diunggah oleh', 'Uploaded By', '업로드한 사람', 'field'),
('Tanggal unggah', 'Upload date', '업로드 날짜', 'field'),
('Fasilitas kredit existing', 'Existing internal credit', '기존 내부 신용 한도', 'field'),
('internal', 'fasility', '', 'field'),
('reverse', 'reverse', '역처리', 'field'),
('Jenis kredit yang', 'Required credit type', '필요한 신용 유형', 'field'),
('Plafon kredit yang diminta', 'Requested credit limit', '신청 신용 한도', 'field'),
('Produk kredit yang', 'Required Credit Produk', '필요한 신용 상품', 'field'),
('Kredit selesai pada umur', 'Loan maturity age', '대출 만기 연령', 'field'),
('Total penghasilan keluarga –', 'Total family income – loan', '가족 총소득 - 대출 상환액', 'field'),
('angsuran kredit', 'installment', '', 'field'),
('Nomor rekening gaji untuk', 'Salary Account Number for', '지급용 급여 계좌 번호', 'field'),
('Gaji suami/istri', 'Spouse’s salary', '배우자 급여', 'field'),
('Angsuran pinjaman', 'Loan installment', '대출 상환액', 'field'),
('Tunjangan tkd suami/istri', 'Spouse''s tkd allowance', '배우자 TKD 수당', 'field'),
('Total penghasilan', 'Total income', '총소득', 'field'),
('suami/istri', '', '', 'field'),
('keseluruhan', '', '', 'field'),
('Disposisi', 'Disposition', '처리 지시', 'field'),
('Review Hasil Upload', 'Review Upload Results', '업로드 결과 검토', 'field');
